MSEP-one/msep.one

godot_project/autoloads/MolecularEditorContext.gd

This function definition was accidentally left outside of https://github.com/MSEP-one/msep.one/commit/124c6fe2004d927df83f74b579396ff0a212bdd1
The change was added to our **devel** branch in [f71003f (diff)](https://github.com/MSEP-one/msep.one/commit/f71003fd128e6188071f9d95ac6c396f9a3f7e1b#diff-e276351b8ff9f3fa9861cf18c32f0b7edb7b4186c0d57c1e8d9b949fe26618fdR417-R418)
To have a stable main branch this fix is needed (current release was manually built with this code in)

Add missing definition caused by a bad merge

---

godot_project/autoloads/about_msep_one/about_msep_attribution_page.gd
godot_project/autoloads/about_msep_one/about_msep_attribution_page.tscn
godot_project/autoloads/about_msep_one/about_msep_one.gd
godot_project/autoloads/about_msep_one/about_msep_one.tscn
godot_project/autoloads/about_msep_one/other_attributions/other_attributions.gd
godot_project/autoloads/about_msep_one/other_attributions/other_attributions.tscn
godot_project/autoloads/about_msep_one/third_party_software/third_party_software.gd
godot_project/autoloads/about_msep_one/third_party_software/third_party_software.tscn
godot_project/theme/theme.tres

- A page for third party software (godot engine, openmm, openff, zeromq, conda, rdkit)
- Displays software name, with a link to web page, version, and license text for each of them
- An additional page for other (non software) content. For now only small molecules library is in there
-----------
Tasks:
- Part 2 of Add Open Source Information for Small Molecules
- Get License Information
DEPENDS ON: https://github.com/MSEP-one/msep.one/pull/3

Improbe the About MSEP.one window with license information about third party software used in the project

---

godot_project/editor/controls/menu_bar/menu_bar.tscn
godot_project/editor/controls/menu_bar/menu_help/menu_help.tscn
godot_project/editor/controls/menu_bar/menu_view/menu_camera/menu_camera.gd
godot_project/editor/controls/menu_bar/menu_view/menu_camera/menu_camera.tscn
godot_project/editor/controls/menu_bar/menu_view/menu_view.gd
godot_project/editor/controls/menu_bar/menu_view/menu_view.tscn

- This mirrors the layout of the RingMenu
- Also moved 'View/Camera Projection' to 'View/Camera/Camera Projection'
-----------
Task: Move Camera menu in the topbar inside the View menu to match new RingMenu layout

Move Camera Topbar/VisualMenu from the root of the topbar to a submenu of the View menu

---

godot_project/addons/runtimespatialgizmo/RuntimeSpatialGizmo/OrthoRotationArcs.gd
godot_project/addons/runtimespatialgizmo/RuntimeSpatialGizmo/OrthoTranslationAxes.gd
godot_project/addons/runtimespatialgizmo/RuntimeSpatialGizmo/OrthoZHandle.gd
godot_project/addons/runtimespatialgizmo/RuntimeSpatialGizmo/OrthoZSurface.gd
godot_project/autoloads/ui_blocker/ui_blocker.gd
godot_project/autoloads/ui_blocker/ui_blocker.tscn
godot_project/editor/controls/editor_viewport_container/widgets/orientation_widget/DrawOrientationWidget.gd
godot_project/project.godot

REPRODUCTION STEPS
- Grab the transform gizmo xy movement tool and move the selection around so that mouse hovers over various UI elements
-- Or any other transform gizmo handle.
- Observe that most UI interactive controls become activated as the mouse hovers over them
------
Task: UI elements become active, while transform gizmo is grabbed

Block UI hover detection while transform gizmo is moved

---

modules/lmdb/thirdparty/capnpSCsub

Regression on capnpSCsub during migration to github
-----------
The following file was reverted during the migration to github. This adds back the changes done on the last days before open-sourcing.

Removed unused linking steps for libs from capnp and kj

---

godot_project/editor/controls/dockers/workspace_docker/simulations_docker/simulations_docker_controls/simulation_settings_panel.gd
godot_project/editor/controls/dockers/workspace_docker/simulations_docker/simulations_docker_controls/simulation_settings_panel.tscn
godot_project/theme/theme.tres

In the 3 settings panels for Simulation Force Fields (Relax,Molecular Simulation, and Validate), add an option for "Molecular Simulation Toolkit"
This should be a pull-down control:
The default option should be "OpenMM"
There should be a grayed out option for "LAMMPS (under development)"
So, the user won't be able to choose anything other than OpenMM. This option should be placed below the Force-Field selectors.

Add a placeholder for Simulation Toolkit

---

godot_project/editor/controls/dockers/workspace_docker/e_workspace_settings_docker/controls/editor_settings/color/confirmation_color_popup.gd
godot_project/theme/theme_3d/available_themes/flat_theme/flat_environment.tres

The bug as written is fixed, however, the bg color varies slightly between Academic and Modern. Also, setting the colors back to Default does not set the color swatches back to the default.
- Go to workspace settings
- Switch to academic view
- Change the background color
- Switch to modern view
- Switch back to academic view
- Observe that the background color is reset to the default, but the settings still shows that the new color is being used
-------
Task: Modern view resets the user specified colors in Academic view

Fix the modern, academic color switching

---

godot_project/project_workspace/workspace_context/structure_context/collision_engine/collision_engine.gd

Reproduction steps:
+ Add a molecular structure
+ Look away from the structure
+ Select "Closest object to pointer" in the Create tab, under Creation Distance
This also happens in orthographic view, even if the structure is on screen but not all the time, there might be another related issue, but this PR is about addressing the crash.

Fix infinite loop when setting the creation distance to "Closest object to pointer"

---

godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/capsule_stick_representation/capsule_stick_representation.gd

-----------
Task: BUG: When hovering a group in **Sticks** or **Enhanced Sticks** representation, all the bonds of the group doesn't highlight, only the bond under the cursor
Preview:

Fix a case where hovering a group in sticks mode highlights only the bond and not the entire group

---

godot_project/editor/controls/dockers/workspace_docker/e_workspace_settings_docker/controls/theme_settings/theme_settings.gd

-----------
Task: BUG: Theme (Movern/Academic view) is part of the undo state, but changing the theme does not create an snapshot

Create an undo Snapshot when Visual Theme is changed

---

godot_project/editor/controls/dockers/workspace_docker/e_workspace_settings_docker/controls/general_settings/general_settings.gd

This allows to Save changes with Ctrl+S without losing them while the UI is focused
-----------
Task: BUG: Project Description and authors are not applyed until text edit edit is unfocused

Push WIP changes to Workspace even before creating an Snapshot when done editing

---

godot_project/editor/controls/screen_capture_dialog/screen_capture_dialog.gd
godot_project/project_workspace/workspace_context/structure_context/selection_db/selection_db.gd

The selection state was properly saved (and restored), but the rendering state was not. Before the snapshot system, changing the selection used to cause the renderer to refresh its state, but now this has to be done explicitly.

Fix missing outline when closing the screen capture popup

---

godot_project/editor/rendering/rendering.gd
godot_project/project_workspace/workspace_context/workspace_context.gd

CRASH
-----------
fix Rendering snapshot edge case issue 🔨
There was an issue related to snapshot implementation of Rendering that
revealed itself in case when snapshot has been applied multiple times
during the same frame.
In case when in the result of snapshot 'apply' operation the structure
has been removed, and then later during the same frame other snapshot
'apply' operation is requested this time re-instantiating the same
structure, such structure was not re-instantiated correctly.
The direct cause for this was incomplete is_instance_valid check(),
such instance is valid at that point but already queued for deletion.
The edge case described in here is happening every time when directly
after running mechanical simulation user decides to add new structure
from library …

fix adding a structure after simulation

---

godot_project/autoloads/about_msep_one/about_msep_attribution_page.tscn

BUG - Text needs word wrapping in attribution boxes.
-----------
ensure auto-wrap on license pages 🔧
Some licenses could not be read in full since lines were too long This commit adds word auto-wrap to ensure this is no longer the case

ensure auto-wrap on license pages 🔧

---

godot_project/autoloads/MolecularEditorContext.gd
godot_project/editor/controls/editor_viewport_container/EditorViewportContainer.gd
godot_project/editor/controls/message_bar/message_bar.gd
godot_project/editor/controls/message_bar/message_bar.tscn
godot_project/editor/controls/workspace_view/WorkspaceMainView.gd
godot_project/editor/input_handlers/molecular_structures/create_object_drag_drop_input_handler.gd
godot_project/editor/input_handlers/molecular_structures/selection_input_handler.gd

Distance calculation feature should be in Nanometers, not pixels
-----------
commit f5bc035effac3339ceea808955908dfb7a3f4643 (HEAD -> pr/show-distances, origin/pr/show-distances)
Author: Jakub Grzesik <kubecz3k@gmail.com>
Date:   Mon Nov 4 14:45:39 2024 +0100
show bond/spring length 📦
This commit will display information about bond/spring length in
message bar
commit 0d06e40d305e0af786ae6a25568d0953626de7c4
Author: Jakub Grzesik <kubecz3k@gmail.com>
Date:   Mon Nov 4 14:44:52 2024 +0100
show distance between hover and selection 📦
This commit will display information about distance between object
which is being hovered and selection
Information is displayed in bottom right corner of the screen

Show distances between hower and selection as well as Bond/Spring length

---

godot_project/editor/controls/editor_viewport_container/widgets/axes_widget/DrawAxesWidget.gd
godot_project/editor/controls/editor_viewport_container/widgets/axes_widget/axes_widget.gd
godot_project/editor/input_handlers/camera_input_handler.gd

- The first fix eliminated inertia when the mouse button is released.
- We should also remove inertia when the user moves the mouse, stops movement, but doesn't release the mouse button.
Task: BUG - Inertia is still applied while the mouse is held down when rotating

Remove rotation inertia for orbiting

---

godot_project/editor/rendering/atomic_structure_renderer/atomic_structure_renderer.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/balls_and_sticks_representation/balls_and_sticks_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/enhanced_sticks_and_balls_representation/enhanced_sticks_and_balls_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/labels_representation/labels_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/single_atom_representation/single_atom_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/sphere_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/springs_representation/springs_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/stick_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sticks_single_atom_representation/sticks_and_single_atom_representation.gd
godot_project/editor/rendering/rendering.gd
godot_project/project_workspace/workspace_context/structure_context/selection_db/atom_selection/atom_selection.gd
godot_project/project_workspace/workspace_context/structure_context/selection_db/selection_db.gd

Bonds disconnected from atoms during rotation
-----------
fix bond independent movement after atom creation 🔨
When user had non selected bond connecting two selected atoms and they
created new atom, the bond moved together with newly created atom
despite the fact the related atoms were standing still (not the bond
nor related atoms were selected at that point)
This issue was caused by the fact in such case shader never gets
information that the bond is no longer connected to any selected atom
This commit fixes the issue by ensuring SelectionDB.set_atom_selection
always refreshes any involved bond
fix bond independent movement after deselection 🔨
When user had non selected bond connecting two selected atoms and they
deselected those atoms one by one, then after doing drag drop selection …

Fix Bonds disconnected from atoms during rotation

---

godot_project/editor/rendering/atomic_structure_renderer/representation/enhanced_sticks_and_balls_representation/enhanced_sticks_and_balls_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sticks_single_atom_representation/sticks_and_single_atom_representation.gd

"Bonds disconnected from atoms during rotation"
-----------
The function has been renamed recently, but it was not updated everywhere

fix non-existing function call 🔨

---

godot_project/editor/controls/dockers/workspace_docker/c_dynamic_context_docker/dynamic_context_controls/inspector_controls/inspector_control_rotation/inspector_control_rotation.tscn
godot_project/editor/controls/dockers/workspace_docker/c_dynamic_context_docker/dynamic_context_controls/inspector_controls/inspector_control_vector3/inspector_control_vector3.gd
godot_project/editor/controls/dockers/workspace_docker/c_dynamic_context_docker/dynamic_context_controls/selection_info.gd
godot_project/project_workspace/workspace_context/structure_context/selection_info.gd

- NanoVirtualMotor has special treatment because their model is facing to the right instead of to the front
- Also modified the rules when positioning the editor controls to expand using both columsn when first column has no text (This is exactly the case of Position and Rotation)
-----------
Tasks:
- Part 2 of BUG: Position and Rotation of Reference shapes are not editable in Selection Information panel
- Part 2 of BUG: Virtual Motors do not show any information in SelectionInformation panel

Add support to editing rotation of virtual objects in Selection Info Panel of the Dynamic Context docker

---

godot_project/editor/input_handlers/molecular_structures/transform_input_handler.gd
godot_project/project_workspace/workspace_context/workspace_context.gd

-----------
Task: When position of Motors and/or Shapes is changed from Selection Info Panel, the transform fizmo does not update to show the new selection center
Preview Before:
https://github.com/user-attachments/assets/ee0e5cbe-1652-4bbb-bdc0-a82b5a2c59ac
Preview After:
https://github.com/user-attachments/assets/6cc3a772-5581-408b-aa15-4b9369185dfa

Update position of the transform gizmo when moving virtual objects using the spinboxes in the Selection Info Panel

---

godot_project/editor/input_handlers/molecular_structures/add_atom_input_handler.gd

-----------
Task: BUG: Is posible to create atoms and bonds in Select Mode

Prevent from creating atoms and bonds with Shift+Click when application is in Select Mode

---

godot_project/editor/controls/dockers/workspace_docker/c_dynamic_context_docker/dynamic_context_controls/3d_preview.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/single_atom_representation/single_atom_representation.tscn
godot_project/project_workspace/workspace_context/workspace_context.gd
godot_project/theme/theme_3d/available_themes/flat_theme/flat_ball.gdshader
godot_project/theme/theme_3d/available_themes/flat_theme/flat_bond.gdshader
godot_project/theme/theme_3d/available_themes/flat_theme/flat_capsule.gdshader

Selected shape preview behaves as it appears inconsistently
-----------
fix selection-preview for flat theme 🔨
Flat theme has never been updated to work in new selection preview
This commit fixes this oversight by applying changes needed for it to
work
refresh selection preview for shapes and motors 🔧
This commit ensures the selection previews for shapes and motors will
update on every motor/shape transform change

Fixes after selection preview rework

---

godot_project/autoloads/initial_info_screen/initial_info_screen.tscn

"Change the Start-Up Splash Screen Text"
-----------
It has been done in order to align the text vertically inside the popup

remove redundant line on top of startup screen 🔧

---

godot_project/autoloads/MolecularEditorContext.gd

"Crash when loading msep1 file from directory without write permissions"
-----------
This commit ensures user is not experiencing crash when trying to load msep1 file without write permission
This change should also serve any problem with file corruption

Fix msep1 file load crash  🔨

---

godot_project/editor/input_handlers/molecular_structures/add_structure_input_handler.gd

Small molecules preview graphical artifacts
-----------
fix small molecules preview glitch 🔨
After rotating camera small molecules had graphical glitch related to
recent multimesh_atom.gdshader changes and inability to correctly
transform atoms towards camera, shader is no longer prepared to serve
objects with local rotation.
Since it's the only instance of such rotation the most straightforward
fix is to not rotate the model at all, this initial (preview) rotation
is not crucial from user perspective

Fix small molecules preview glitch

---

godot_project/project_workspace/structs/atomic_structure.gd
godot_project/utils/workspace_utils.gd

'Color snapshot' nomenclature seems misleading after introduction of snapshot api
This commit removes unused function and renames the other one in such way it should not get confused with what snapshots are

Clean up 'color snapshot' semantics 🔧

---

godot_project/editor/controls/workspace_view/tab_bar_active_workspaces.gd
godot_project/editor/input_handlers/molecular_structures/add_structure_input_handler.gd
godot_project/editor/rendering/virtual_anchor_and_spring_renderer/virtual_anchor_preview.tscn
godot_project/project_workspace/workspace_context/structure_context/selection_db/selection_db.gd

This commit cleanups startup warnings, such as:
- unused variables
- vanished nodes
Vanished node warning was caused by the fact some parent scenes has changed but child scene still tried to overwrite values on nodes which no longer exists

cleanup startup warnings 🔧

---

godot_project/autoloads/MolecularEditorContext.gd

----------
Task: Move Camera menu in the topbar inside the View menu to match new RingMenu layout
- This was a bug detected during feedback: docker should not scroll to show the entire highlighted category

Fix a corner case where side docker would not scroll to focus the view on the requested highlighted category

---

godot_project/editor/controls/dockers/workspace_docker/c_dynamic_context_docker/dynamic_context_controls/inspector_controls/inspector_control_bond_order/inspector_control_bond_order.gd

""Sticks" doesn't have double or triple bond view, but there is a setting to adjust it"
-----------
disallow stick rendering bond order edit 🔧
This commit ensures user is not able to edit selected bond order in Stick representation (which do not visualize bond order)

disallow stick rendering bond order edit 🔧

---

godot_project/editor/controls/editor_viewport_container/widgets/orientation_widget/DrawOrientationWidget.gd

- Add some atoms to the workspace and select them
- Click on one of the orientation widget axis
- Observe how while snapping to axis happens orientation widget shakes
Task: Orientation widget shakes when axis is clicked

Prevent orientation widget wobble

---

godot_project/editor/controls/menu_bar/menu_help/menu_help.gd

It was hidden because it was already accesible from the Application Menu, but removing it causes a regression where 'Tutorials and Documentation' doesn't work on this platform
Task: BUG - Tutorial PDF doesn't launch **ON MACOS** when selected from the menu bar pulldown menu
-----------

Show 'Help > About MSEP.one' menu item in MacOS

---

godot_project/editor/controls/dockers/workspace_docker/c_dynamic_context_docker/dynamic_context_controls/apply_atoms_to_shape.tscn

Task: "Apply Atoms to Shapes" section UI is not correctly set up and stretches incorrectly
-----------

Correct alignment of element picker in 'Appy atoms to shape' panel

---

godot_project/editor/controls/workspace_view/controls/structure_selector/structure_child_list/structure_child_list.gd

"Crash on group cut"
-----------
fix crash on group cut 🔨
This commit fixes a crash that happens when user is cutting a structure
Crash happened in very specific scenario in which:
1. User creates two groups, one parent of the other
2. User ensures the child structure is selected/edited and merges it up
3. User ensures the parent structure is selected/edited and performs
cut operation on it
The direct cause of the crash was insufficient check on 'parent
structure' availability inside StructureChildList

Fix crash on group cut

---

godot_project/editor/input_handlers/molecular_structures/create_object_drag_drop_input_handler.gd

"Preview Atom Can be Wrong Size in Perspective mode"
-----------
select source atom when performing drag-drop 🔧
This commit ensures the source atom of drag and drop is selected.
It's done in order to ensure preview is being visualized at creation
distance which is expected by the user
(in case when selected atom was at significantly different position
from drag-drop source atom the preview was visualized nearby that
selection)

Select source atom when performing drag-drop 🔧

---

godot_project/editor/controls/dockers/workspace_docker/e_workspace_settings_docker/controls/editor_settings/color_settings.gd
godot_project/theme/theme_3d/theme_3d.gd

Fixes: BUG - Background color selection box doesn't change when changing themes
-----------
The color boxes in the settings panel were not updated when switching from one theme to another.

Update the color settings panel when the theme is changed

---

godot_project/editor/input_handlers/molecular_structures/selection_input_handler.gd

Reproduction steps:
+ Create a shape
+ In atom create mode, enable "Snap to reference shape" in the creation distance panel
+ Hover a shape

Fix a crash when 'Snap to reference shapes' is enabled

---

godot_project/python/scripts/openmm_server.py

'ascii' codec can't decode byte 0xe2 in position 1467: ordinal not in range(128) #95 
-----------
The error occurred because Python was trying to read the file using ASCII encoding by default, but encountered a non-ASCII character (byte 0xe2) which couldn't be decoded.
This is a common issue that can occur specifically on Linux because different operating systems have different default file encodings:
- Windows typically defaults to cp1252 (a superset of ASCII)
- macOS typically defaults to UTF-8
- Linux's default can vary, but often defaults to ASCII
So we explicitly set `utf-8` as the default encoding.

Fix: Specify utf-8 encoding to ensure proper handling of extended characters

---

godot_project/editor/input_handlers/camera_input_handler.gd

Fixes: Holding the SHIFT key to move the camera faster is ignored by the camera handler at specific times.
Example: right after importing something from the library, but before moving the mouse.
For some unknown reason, `InputEventKey` doesn't contains which modifier keys are pressed at this specific time.
Instead, this PR directly check against the `Input` class which always have up to date info.

Shift key is sometimes ignored by the camera input handler

---

godot_project/editor/controls/dockers/workspace_docker/e_workspace_settings_docker/controls/visibility_settings/visibility_settings.gd
godot_project/editor/controls/dockers/workspace_docker/e_workspace_settings_docker/controls/visibility_settings/visibility_settings.tscn
godot_project/editor/controls/editor_viewport_container/widgets/camera_widget/CameraWidget.gd
godot_project/editor/input_handlers/camera_input_handler.gd
godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd
godot_project/editor/input_handlers/molecular_structures/transform_input_handler.gd
godot_project/project_workspace/structs/representation_settings.gd

The feature showing potential atoms positions is currently hidden behind a shortcut. 
+ Add a toggle under the Visibility settings (in the workspace docker)
- When enabled, the ghost positions are always visible (as long as there is a selection)
+ When the Alt key is held:
- Create mode is automatically enabled
- Force the handler as an exclusive consumer to hide the transform gizmo which appears on top of the atoms candidates

Improve "auto atoms posing" discoverability and usage

---

godot_project/autoloads/data/ElementData.gd
godot_project/autoloads/nano_editor_clipboard/nano_editor_clipboard.gd
godot_project/autoloads/openmm/openmm_payload.gd
godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd
godot_project/editor/rendering/atom_autopose_preview/atom_autopose_preview.gd
godot_project/project_workspace/structs/atomic_structure.gd

This PR forces the auto pose feature to always use the selected atomic element, instead of switching to oxygen or hydrogens based on the parent atom free valence.
Clicking a candidate will now pick a smaller bond order if necessary.

Fix the auto pose recommendations and bond order

---

godot_project/editor/controls/dockers/workspace_docker/simulations_docker/simulations_docker_controls/simulation_tools_panel.gd

In the simulation docker, pressing "End simulation" will cause openMM to stop processing the simulation, but MSEP will keep playing the cached frame.
This PR simply pauses the playback (the user can resume until the end of the processed sim)

Pause the simulation playback when pressing the 'End simulation' button

---

godot_project/project_workspace/workspace_context/workspace_context.gd

Finding the root cause for that one was tricky.
When deleting a structure, if a simulation is running, two snapshots are taken to avoid merging two user operations under a single undo step.
But reapplying the final state was inconsistent because `_modified_structure_contexts` is not part of the snapshot and still contains a reference to the deleted structures. This PR clears this array on restore.
I don't think it should be part of the snapshot, since there's already code in place to take care of the orphaned structures, but if that's not right, I can put it in the snapshot data.

Fix assert after deleting a structure during a simulation

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd

The atom suggestions wouldn't re appear until the next mouse event if the camera was moved with the keyboard.
This is because a wrong condition in handle_inputs_resume.

Fix atom suggestions not being restored after moving the camera with the keyboard

---

godot_project/editor/controls/dockers/workspace_docker/simulations_docker/simulations_docker_controls/atomic_structure_model_validator.gd
godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd
godot_project/editor/rendering/atom_autopose_preview/atom_autopose_preview.gd
godot_project/utils/spatial_hash_grid/spatial_hash_grid.gd

There are two main performance issues with the atom auto posing feature:
+ Drawing 100+ circles, connections and labels is expensive
+ When two candidates are close to each other, they are merged into a single one, connecting all the parent atoms.
- The current implementation of this check is O(n²)
- This is what causing the several seconds freeze when loading a file or making a large selection at once.
This PR limits the maximum amount of candidates on screen (computed and drawn).
It also takes the spatial hash grid from the "atoms overlap detection" and moves it to a generic class. This way we can reuse it to detect the candidates to merge and speed up that step.

Auto posing freezes MSEP when loading a large file

---

godot_project/autoloads/shader_precompiler/shader_precompiler.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/billboard.gdshaderinc
godot_project/editor/rendering/atomic_structure_renderer/representation/hydrogens.gdshaderinc
godot_project/editor/rendering/atomic_structure_renderer/representation/labels_representation/assets/label_material.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/labels_representation/assets/labels_representation.gdshader
godot_project/editor/rendering/atomic_structure_renderer/representation/labels_representation/labels_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/single_atom_representation/assets/single_atom_representation.gdshader
godot_project/editor/rendering/atomic_structure_renderer/representation/single_atom_representation/single_atom_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/assets/multimesh_atom.gdshader

The single atom representation shader is using a different billboard code that's not working, making unconnected atoms invisible in stick view.
This PR moves the billboard code (used by sticks, labels and sphere views) under a common shader include.
It's no longer necessary to pass the camera basis vector as uniform because that data is included in INV_VIEW_MATRIX already, so code related to that was removed.

Fix single atoms not visible in stick view

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd
godot_project/utils/spatial_hash_grid/spatial_hash_grid.gd

If a candidate would overlap an existing atom, remove it from the suggestions.

Prevent auto posing from suggesting atoms inside existing atoms 

---

godot_project/project_workspace/workspace_context/history/history.gd

When changing the active group using the group bar at the top of the workspace, the simulation stops.
This is because the change group action was renamed but the whitelist wasn't updated.

Fix changing active group interrupts the simulation

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd
godot_project/editor/rendering/atom_autopose_preview/atom_autopose_preview.gd
godot_project/editor/rendering/atomic_structure_renderer/atomic_structure_renderer.gd
godot_project/editor/rendering/rendering.gd

The atoms auto posing handler now stays visible, even if other handlers (exclusive or higher priority) are active, and even if no input events are received.
This PR also forces a redraw when the create mode is enabled (instead of waiting for the next input event to draw the candidates)

Keep autoposing visible when hovering an atom or other UI elements

---

godot_project/project_workspace/workspace_context/workspace_context.gd

Fixes a crash that occurs when box selecting a hidden virtual object (anchor, or motor)
Task: CRASH - Invisible objects cause crash errors
Before:
https://github.com/user-attachments/assets/e923f8c8-17e5-4b28-802c-0e4c324c4cf2
After:
https://github.com/user-attachments/assets/f25ae573-ab83-4b0c-a08b-857645bc67c9

CRASH FIX: Ensure virtual objects and groups are marked 'dirty' when visibility is changed

---

godot_project/autoloads/MolecularEditorContext.gd
godot_project/editor/rendering/atom_autopose_preview/atom_autopose_preview.gd

Task: CRASH - Create a new Workspace, then click on welcome tab

CRASH FIX: Fix crash when navigating to homepage while Autopose preview is active

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd

This happens if you have atom candidates on screen, and select too many atoms at once. The auto posing feature gets disabled but the previous candidates were not cleared, so they stayed up on screen.

Fix invalid candidates appearing on screen, not connected to any atoms

---

godot_project/editor/controls/dockers/workspace_docker/a_create_docker/auto_create_bonds_panel.tscn
godot_project/theme/Gidole-Regular.ttf.import

Task: Redundant letter "i" before "No atoms selected" (and other info text issues that could perhaps have different tickets)
Note: I refrained myself from including **Noto Regular Emoji** in the project, the application will already pick it up if the system has it installed. If this continues to be a problem we could just include the font in the repository (23Mb) and whitelist the characters we use (something i didn't know at first, _we have to whitelist unicode characters_)

Fix wrong information character displayed in Auto Create Bonds panel

---

godot_project/autoloads/MolecularEditorContext.gd
godot_project/editor/controls/workspace_view/WorkspaceMainView.gd
godot_project/project_workspace/workspace.gd
godot_project/project_workspace/workspace_context/workspace_context.gd

- Zoom level in orthogonal projection will be restored
- Currently edited group will be restored
Tasks:
BUG - Ortogonal Camera is not restored properly after saving and restoring a file
BUG - Save files not maintaining UI position in groups

Restore some of the old state when loading a saved project

---

godot_project/utils/reference_shape/reference_shape_utils.gd

- This should prevent crashes caused by running out of limit when filling an unreasonably large shape with atoms
Task: CRASH - Filling a large shape with atoms cause the application to close silently

Set a reasonable shape size limit to reference shapes

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd

dont wait for the mouse cursor to enter the viewport
Task: the Show Potential Atom Positions toggle doesn’t update the Editor Window until the mouse moves into the Editor Window.

When switching the 'Show Potential Atom Positions' toggle in Workspace Settings, immediately toggle the visibility of atom candidates

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd

- When the type of object is created, only show if creating atoms and bonds
- When simulation starts, hide candidates until simulation ends
Task: CRASH - Clicking on Atom after running a simulation

Update the visibility of Atom Candidates when some sensible settings changes

---

godot_project/project_workspace/structs/nano_molecular_structure.gd
godot_project/project_workspace/structs/nano_structure.gd
godot_project/project_workspace/structs/nano_virtual_anchor.gd
godot_project/project_workspace/structs/nano_virtual_motor.gd
godot_project/project_workspace/workspace.gd
godot_project/utils/workspace_utils.gd

Fixes: "Add Star Gears Project to Sample Library - The file doesn’t seem to import correctly. Neither of the motors are attached to groups"
Springs, anchors and motors were pointing at the old structures id (from before the import), causing various issues. 
This PR adds a new `init_remap_structure_ids()` method in `NanoStructure`, called automatically when a workspace is imported from another workspace. If the structure is holding a reference to another structure, it has to update that link here.

Fix star gears missing connections

---

godot_project/editor/controls/dockers/workspace_docker/c_dynamic_context_docker/dynamic_context_controls/connect_motors_to_groups_panel.gd

Snapshot cannot happen while tree is being edited, this is because of internal state of Tree class causing errors when trying to modify it while is being edited, and this can happen if we edit the tree while a simulation is happening.
For this reason we use call_deferred to run snalshot_moment
Task: CRASH - Unlinking a motor during a simulation

Wait until the end of the frame to snapshot moment when (dis)connecting groups form motors

---

godot_project/editor/controls/dockers/workspace_docker/groups_docker/groups_docker_controls/nano_groups_list.gd
godot_project/editor/input_handlers/molecular_structures/selection_input_handler.gd
godot_project/editor/rendering/atomic_structure_renderer/atomic_structure_renderer.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/balls_and_sticks_representation/balls_and_sticks_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/enhanced_sticks_and_balls_representation/enhanced_sticks_and_balls_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/labels_representation/labels_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/selectable.gdshaderinc
godot_project/editor/rendering/atomic_structure_renderer/representation/single_atom_representation/single_atom_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/assets/multimesh_atom.gdshader
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/assets/multimesh_atom_material.tres
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/assets/sphere_material.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/sphere_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/springs_representation/spring_renderer/spring.gdshader
godot_project/editor/rendering/atomic_structure_renderer/representation/springs_representation/spring_renderer/spring_renderer.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/springs_representation/springs_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/capsule_stick_representation/assets/bond_capsule.gdshader
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/capsule_stick_representation/assets/capsule_stick_material.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/capsule_stick_representation/capsule_stick_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/cylinder_stick_representation/assets/bond_cylinder.gdshader
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/cylinder_stick_representation/assets/bond_cylinder_material.tres
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/cylinder_stick_representation/assets/cylinder_stick_material.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/cylinder_stick_representation/cylinder_stick_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/stick_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sticks_single_atom_representation/sticks_and_single_atom_representation.gd
godot_project/editor/rendering/rendering.gd
godot_project/project_workspace/workspace_context/workspace_context.gd

When selecting a group in groups panel, ensure it selects all subgroups
-----------
Author: Jakub Grzesik <kubecz3k@gmail.com>
Date:   Tue Nov 19 09:33:59 2024 +0100
grayscale non editable groups 🔧
This commit will make it obvious for the user which groups can be
edited and which are non-editable
It accomplishes this by making non editable structures desaturated,
grayscaled
commit e606e3917118db9e6390bae7641ce64a4c0c39d2
Author: Jakub Grzesik <kubecz3k@gmail.com>
Date:   Mon Nov 18 07:49:12 2024 +0100
make group selection downwards 🔧
So far when selecting a group whole tree branch has been selected
always, no matter which group user has chosen.
This pr changes this behavior, now when group is clicked it will be
selected together with all groups which are beneath (so parent groups
are no …

Improve group selection 

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd
godot_project/editor/input_handlers/molecular_structures/transform_input_handler.gd

Fixes: BUG - Clicking to select an atom makes the transform gizmo disappear until mouse move
+ The transform gizmo visibility depends on the variable `_other_handler_has_exclusivity` which is not always up to date.
This is replaced with a call to the editor viewport instead.
+ The autoposing handler sometimes returns false in `forward_input` even when it has exclusivity, causing other inconsistencies. This was fixed too.

Fix transform gizmo not appearing until next input event

---

godot_project/project_workspace/structs/nano_structure.gd
godot_project/project_workspace/workspace.gd
godot_project/utils/workspace_utils.gd

Import workspace now works with any group hierarchy, including when an child anchor is connected to atoms from an ancestor structure.
+ Fixes anchor not respecting the selected placement options
+ `_create_in_guid` from Workspace is now internal again
+ Code should be easier to follow

Fix `import workspace` logic & code cleanup

---

godot_project/editor/controls/dockers/workspace_docker/groups_docker/groups_docker_controls/nano_groups_list.gd

Task: BUG: Changing editable group or selection form the Groups panel no longer generates UNDO steps

Add UNDO steps when selecting or changing edited group from Groups panel

---

godot_project/editor/rendering/atomic_structure_renderer/representation/single_atom_representation/single_atom_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/sphere_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/stick_representation.gd

Fixes: "BUG: When hovering an atom of the current edited group, the entire group highlights instead of only the atom (this is meant to happen only if atoms are grouped, wich is not the case)"
This PR prevents highlighting the whole structure if that structure is the current active group.

Fix invalid highlight on hover

---

godot_project/editor/controls/template_library_dialog/template_library_dialog.gd

Fixes: "Move Star Gear to Top of Library list"
This PR keeps the alphabetical order of the `Import Template` dialog, but moves all msep files at the begining.
The alternative would have been to manually add a numbered prefix to every file (like "01_star_gears"), but that approach means every time we add a new file in the middle of the list, we need to rename everything that comes after.

Reorder the template library file list

---

godot_project/editor/rendering/atomic_structure_renderer/representation/single_atom_representation/single_atom_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/sphere_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/stick_representation.gd

Follow up to #139 
The structure highlight is updated when the active structure changes.

Update structure highlight on group change

---

godot_project/editor/controls/dockers/workspace_docker/groups_docker/groups_docker_controls/nano_groups_list.gd
godot_project/editor/input_handlers/molecular_structures/dialog_input_handler.gd
godot_project/editor/input_handlers/molecular_structures/selection_input_handler.gd
godot_project/project_workspace/workspace_context/structure_context/structure_context.gd

Fixes: "CRASH - Nesting Groups"
This PR ensures the selection logic works as Jonathan described it:
From the initial state:
+ When selecting the SmallBearing group:
> It selects small bearing and its children, as they are part of smallBearing.
+ When selecting Center1:
> If you click on center 1, because you are at the top level, you will select smallBearing. If you were inside smallBearing, clicking on center 1 would select center 1 and any children of center 1.
+ When selecting SingleAtom, then trying to multiselect Center1
> If you have singleAtom selected then multiselect center1, you would select smallBearing and all its children, along with singleatom.

Fixes the selection logic

---

godot_project/editor/rendering/reference_shape_renderer/reference_shape_renderer.gd
godot_project/editor/rendering/rendering.gd

`is_instance_valid()` doesn't take into account if a node is queued for deletion.
Because of this, snapshot of ReferenceShape was applied to the reference shape being deleted instead of to the new duplicate being created
Also added similar guards for motors and anchors
Task: CRASH - Created invisible Torus, crashed trying to move it.

Dont apply snapshot state to a dying Reference Shape

---

godot_project/editor/rendering/atomic_structure_renderer/atomic_structure_renderer.gd
godot_project/project_workspace/workspace_context/workspace_context.gd

- Renderer was being recreated, but initialization code was not being run, causing it to be disconnected from the 'xxx_changed' signals of the original molecule
- Also fixed an annoyig bug where deleting a group and ondoing it would print a lot of errors about connecting signals which are already connected
Task: BUG - SIMULATION PUT IN BAD STATE

Fix corner case when undoing deletion of a group

---

godot_project/project_workspace/workspace_context/structure_context/collision_engine/collision_engine.gd

Task: CRASH - Doing cut and paste of group with hidden springs and anchors.

Fix corner case causing a crash when deleting a group during a simulation

---

godot_project/project_workspace/workspace.gd

- This fixes a side effect that caused signals connecting from a workspace tab affecting renderers of a different tab
Task: MAJOR BUG - Opening multiple instances of the same file, creates visibility entanglement

Fix check for 'Workspace.has_structure(...)'

---

godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/sphere_representation.gd
godot_project/utils/segmented_multimesh/segmented_multi_mesh.gd

Fixes: CRASH - Changing Visualized Radius setting settings while in Enhanced Sticks mode
`BallsAndStickRepresentation` is listening directly to the `balls_and_sticks_size_source_changed` signal, which will trigger the radius update whether the representation is active or not. And if the representation is not active, it can be outdated, meaning the underlying representation doesn't match the structure contents.
It would be better to do this check in `BallsAndStickRepresentation` instead of in `SphereRepresentation` but there's no easy way to tell if a given representation is active or not.

Fix crash on atom radius change

---

godot_project/editor/controls/dockers/workspace_docker/simulations_docker/simulations_docker_controls/simulation_tools_panel.gd

TASK: BUG - After a simulation failure, clicking the Play Simulation button twice makes it appear that the simulatoin is running

Make more obvious you cannot replay an errored simulation when no frames have been received

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd

Fixes: "BUG - Atom Placement Hints disappear when using select all"

Show a warning message when using the auto posing feature with more than 50 atoms

---

msep.code-workspace
scripts/build_editor_debug.windows.sh

- MingW is required in Windows by LMDB module
No Task

Configure VSCode Workspace to debug Windows binaries with MingW64 compiler

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd

Fix: BUG - Changing views with atom selected can continue to show atom position suggestions

Make atoms suggestions only appear in balls and sticks representation

---

godot_project/editor/controls/workspace_view/controls/toggle_ring_menu_button.tscn

Fixes: Clicking on the "action ring icon" while the Action Ring is up should lower the Action Ring
If the ring menu is open, any click outside the ring will close it, and forward the even to the control behind the cursor.
If the cursor is over the bottom right button, the ring menu will still close, but the button will catch the click (and release), and trigger the `toggle_ring_menu` action, causing the menu to open again.
This is because the button press is triggered on the mouse release (like every other button), but that release happens several frames after the menu was closed, but before the close animation is complete, which makes it look like the button isn't working.
This PR changes the `action_mode` from `released` to `pressed` so the button is triggered immediately, when the ring …

Fix the bottom ring menu button not closing the ring menu

---

godot_project/project_workspace/structs/nano_molecular_structure.gd

Tasks:
- BUG - Even though springs are invisible, they absorb mouse clicks. Saving spring visibility is broken
- BUG: Creating a group of atoms makes it's hidden springs visible
| **Before** | **After** |
|-------------|-----------|
| ![image](https://github.com/user-attachments/assets/de73ae3c-2721-4755-a947-9b055cd025f7) | ![image](https://github.com/user-attachments/assets/4a3224f7-ded1-41af-8bed-21314b06c343) |

When an anchor is saved as hidden, hide it's springs when loading the file next time

---

godot_project/editor/rendering/structure_preview/structure_preview.gd

A corrupt version of the scene is being loaded when using preload
Task: CRASH - LOADING SMALL MOLECULES

Replace preloading for loading

---

godot_project/autoloads/busy_indicator/sprites/spriteChain.svg.import
godot_project/editor/controls/ring_menu/nano_ring_menu/ring_menu_ui/ring_menu_3d/ring_inner_circle/assets/ring_inner_circle_back_glow.png.import
godot_project/editor/controls/ring_menu/nano_ring_menu/ring_menu_ui/ring_menu_3d/side_button/assets/back_ico.png.import
godot_project/editor/icons/icon_Atom.svg.import
godot_project/editor/rendering/atomic_structure_renderer/representation/labels_representation/assets/labels_representation_atlas.png.import
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/assets/atom_noise_atlas.png.import
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/assets/inner_rim.png.import
godot_project/editor/rendering/atomic_structure_renderer/representation/springs_representation/spring_renderer/assets/chain-alpha.png.import
godot_project/editor/rendering/atomic_structure_renderer/representation/springs_representation/spring_renderer/assets/chain_Material_Normal.png.import
godot_project/editor/rendering/atomic_structure_renderer/representation/springs_representation/spring_renderer/assets/chain_Material_OcclusionRoughnessMetallic.png.import
godot_project/editor/rendering/atomic_structure_renderer/representation/springs_representation/spring_renderer/assets/chain_chain.png.import
godot_project/editor/rendering/resources/white.png.import
godot_project/editor/rendering/virtual_motor_renderer/asset/linear_sprite.svg.import
godot_project/editor/rendering/virtual_motor_renderer/asset/rotary_sprite.svg.import
godot_project/editor/rendering/virtual_motor_renderer/motor_link_renderer/assets/MotorLink_dashed-line.png.import
godot_project/project.godot

Export to MacOS is blocked if this setting is disabled.
Enabling it only for macos using the feature field in the export options doesn't work, so this is enabled project wide.

Enable etc2 texture compression required for macos export

---

godot_project/editor/controls/workspace_view/tab_bar_active_workspaces.gd

Task: BUG: Workspace Tab for empty workspace created when launching MSEP doesn't have a close button utin switching to another tab and back

Fix the close button now showing for the empty workspace that opens with MSEP

---

godot_project/editor/controls/general/nano_file_dialog.gd

The node layout of FileDialog changed in https://github.com/godotengine/godot/pull/88673 Because of that there's a new LineEdit, usually hidden, in the same path as before, but used to filter files (Using **[Ctrl|Cmd]+F** shortcut) Our asserts didn't protect us from this change because we still got the same types of nodes in the same deepness
Task: BUGS - New Godot Version Issues

FileDialogs: Connect signals to the right LineEdit

---

godot_project/autoloads/PeriodicTable.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/labels_representation/labels_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/single_atom_representation/single_atom_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/sphere_representation/sphere_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/capsule_stick_representation/capsule_stick_representation.gd
godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/cylinder_stick_representation/cylinder_stick_representation.gd
godot_project/editor/rendering/world_environment.gd

Task: CRASH: MSEP doesn't work efter exporting with Godot 4.4.1

Replace some preloading for loading to avoid cyclic dependencies after export
