godot_project/autoloads/about_msep_one/about_msep_attribution_page.gd
godot_project/autoloads/about_msep_one/about_msep_attribution_page.tscn
godot_project/autoloads/about_msep_one/about_msep_one.gd
godot_project/autoloads/about_msep_one/about_msep_one.tscn
godot_project/autoloads/about_msep_one/other_attributions/other_attributions.gd
godot_project/autoloads/about_msep_one/other_attributions/other_attributions.tscn
godot_project/autoloads/about_msep_one/other_attributions/sfx_attribution_list.gd
godot_project/autoloads/about_msep_one/other_attributions/sfx_attribution_list.tscn
godot_project/autoloads/about_msep_one/other_attributions/sfx_panel.gd
godot_project/autoloads/about_msep_one/other_attributions/sfx_panel.tscn
godot_project/autoloads/about_msep_one/third_party_software/third_party_software.gd
godot_project/autoloads/about_msep_one/third_party_software/third_party_software.tscn
godot_project/autoloads/attributions/attributions.gd
godot_project/autoloads/attributions/attributions.tscn
godot_project/autoloads/attributions/resource_attribution/resource_attribution.gd
godot_project/autoloads/editor_sfx/sfx/close_window_unused_attribution.tres
godot_project/autoloads/editor_sfx/sfx/materialize_1_attribution.tres
godot_project/autoloads/editor_sfx/sfx/menu_window_and_delete_1_attribution.tres
godot_project/autoloads/editor_sfx/sfx/mouse_up_1_attribution.tres
godot_project/autoloads/editor_sfx/sfx/rollover_1_attribution.tres
godot_project/project.godot
godot_project/theme/theme.tres

- A custom resource was created to collect information about third party assets
- A custom control is used to dinamically populate information about audio streams
- It is possible to enable playback of the sfx in the about dialog, but is disabled by default
-----------
Task:
- Add Open Source Information for Audio Files included in the project

Add attributions for used sound effects

---

godot_project/project_workspace/workspace_context/history/history.gd
godot_project/project_workspace/workspace_context/workspace_context.gd

Fixes the following bug:
+ Run a simulation
+ Create an atom (or do anything not whitelisted)
+ Undo
-> The simulation AND user operation is reverted, instead of only the last operation.
This PR applies the simulation and the user action in two separate snapshots instead.

Ensure 'Apply simulation state' is always stored in its own snapshot, separate from other user actions

---

godot_project/editor/controls/editor_viewport_container/widgets/axes_widget/axes_widget.gd

When the camera is moved with the mouse scroll wheel. We've received several complaints that this makes it difficult to make fine adjustments. We should remove the intertia.
Task: Remove intertia from camera controls

Remove scroll wheel inertia and adjust the scroll speeds

---

godot_project/editor/rendering/rendering.gd
godot_project/editor/rendering/virtual_motor_renderer/asset/axle.gdshader
godot_project/editor/rendering/virtual_motor_renderer/virtual_motor_renderer.gd
godot_project/editor/rendering/virtual_motor_renderer/virtual_motor_renderer.tscn

-----------
Task: Motor Axel is rendering incorrectly
https://github.com/user-attachments/assets/98180d7a-9913-44e4-b292-992e5a9834c7

VirtualMotorRenderer: Change how 'distance_to_camera' is calculated depending on if camera is orthogonal or perspective

---

godot_project/editor/controls/dockers/workspace_docker/c_dynamic_context_docker/dynamic_context_controls/selection_info.gd

-----------
Task: Show Total Atoms Selected
Preview:

Add a summary to the Selection Info Panel with total count of selected items per type

---

godot_project/autoloads/about_msep_one/third_party_software/third_party_software.gd

ensure openmm license can be seen

---

godot_project/editor/controls/dockers/workspace_docker/simulations_docker/simulations_docker_controls/atomic_structure_model_validator.gd

Task: BUG: clicking on an atomis overlaping alert made Warning icon dissapear, and filter to show and hide warnings stopped woring

When updating items in the Alers Panel mantain the Unicode character prefix on it

---

godot_project/project_workspace/workspace_context/structure_context/selection_db/atom_selection/atom_selection.gd

-----------
Task: Growing this selection does not select the pointed bond
Before:
After:

Fix a corner case when growing a selection left some bonds unselected

---

godot_project/autoloads/MolecularEditorContext.gd
godot_project/autoloads/openmm/openmm.gd
godot_project/autoloads/ui_blocker/ui_blocker.gd
godot_project/editor/controls/editor_viewport_container/widgets/axes_widget/axes_widget.gd
godot_project/project_workspace/file_format/external/pdb_format_saver.gd
godot_project/project_workspace/file_format/external/xyz_format_saver.gd
godot_project/project_workspace/workspace_context/history/history.gd
godot_project/project_workspace/workspace_context/structure_context/collision_engine/collision_engine.gd

Clean up for the startup warnings

remove startup warnings

---

godot_project/autoloads/data/color_palettes/Corey.tres
godot_project/autoloads/data/color_palettes/JMol.tres
godot_project/autoloads/data/color_palettes/Koltun.tres
godot_project/autoloads/data/color_palettes/MSEP.tres
godot_project/autoloads/data/color_palettes/PubChem.tres
godot_project/autoloads/data/color_palettes/Rasmol.tres
godot_project/autoloads/data/color_palettes/periodic_table_color_palette.gd

-----------
Part 1 of Task: Change the Colors of the Academic View to the CPK colors
Related to #34

Create color palettes for Periodic Table of elements

---

godot_project/project_workspace/workspace_context/structure_context/selection_info.gd

----------
Tasks:
- Part 1 of BUG: Position and Rotation of Reference shapes are not editable in Selection Information panel
- Part 1 of BUG: Virtual Motors do not show any information in SelectionInformation panel
- BUG: Selected VirtualAnchor and Springs show not information at all in Selection Information panel

Support to edit position of virtual objects in Selection Info Panel of the Dynamic Context docker

---

godot_project/autoloads/initial_info_screen/initial_info_screen.tscn

"Change the Start-Up Splash Screen Text"
-----------
Update startup information

Update startup information

---

godot_project/editor/input_handlers/molecular_structures/create_object_drag_drop_input_handler.gd

"Fixed distance drag-drop atom creation does not work"
-----------
This commit fixes drag drop atom creation on fixed distance

fix drag-drop atom creation on fixed distance 🔨

---

modules/lmdb/thirdparty/capnpSCsub

This was a leftover from last changes to the build scripts

Fix MacOS build script

---

godot_project/project_workspace/workspace_context/structure_context/selection_db/atom_selection/atom_selection.gd

"Shrink selection deselects all"
-----------
This commit fixes selection shrink, before the shrink simply deselected all

fix selection shrink 🔨

---

godot_project/editor/rendering/atom_autopose_preview/atom_autopose_preview.gd

Task: CRASH - Creating Motor
**Repro Steps:**
https://github.com/user-attachments/assets/314c68a8-ee39-4a2f-a8b2-ebbf90e1ff04

Fix crash on autopose preview when a virtual object is selected along with atoms

---

godot_project/documentation/video_tutorials/1_create_spinning_molecule.ogv

Task: Decompression Artifacts in Tutorial Videos

Reupload tutorial video without graphic artifacts

---

godot_project/editor/controls/video_tutorials_dialog/icons/window_view.svg
godot_project/editor/controls/video_tutorials_dialog/icons/window_view.svg.import
godot_project/editor/controls/video_tutorials_dialog/video_player.gd
godot_project/editor/controls/video_tutorials_dialog/video_player.tscn

Task: UI Bug - When in Full Screen video playback mode, the minimize button shouldn't read "Full Screen"

Change text and icon of 'Full Screen' if the Turotial Video Player button while in full screen

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd

- This prevents bugs creating atoms in the currently edited group in the position of candidates suggested for others groups
Task: BUG: Autopose allows to create strange hybrid groups

Limit autoposing feature only to selected atoms of the currently edited group

---

godot_project/editor/controls/editor_viewport_container/widgets/axes_widget/axes_widget.gd

Task: BUG - Can't move the camera with the keyboard after zooming in or out

Flag mouse wheel movement as complete whe it has finished

---

godot_project/autoloads/about_msep_one/about_msep_one.tscn

Task: Add MSEP Foundation to Copyright area.

Update copyright notice to mention MSEP Foundation

---

godot_project/editor/controls/dockers/workspace_docker/simulations_docker/simulations_docker_controls/relax_tools_panel.tscn

TASK: Change Relaxation label from the Relax panel: from "All visible molecules" to "All molecules"

Clarify all molecules will be relaxed (Non visible ones too)

---

godot_project/editor/input_handlers/molecular_structures/add_posing_atom_input_handler.gd

Fixes: BUG - Atom Position Recommendations should disappear during relaxation

Hide atoms suggestions during relaxation

---

godot_project/autoloads/openmm/openmm.gd
godot_project/autoloads/openmm/simulation_data.gd
godot_project/editor/controls/dockers/workspace_docker/simulations_docker/simulations_docker_controls/openmm_failure_tracker.gd
godot_project/python/scripts/openmm_server.py

- MSEP can now continue working even if the OpenMM server crashes with unexpected result
- Even if server crashes, you can load a different file and simularion and relaxation will continue working
Task: BUG - Model Won't Relax

Improve comunication with OpenMM server, making messages non blocking when possible

---

godot_project/editor/rendering/atomic_structure_renderer/representation/stick_representation/stick_representation.gd

Task: BUG: Bond(s) left behind when transforming
| **Before** | **After** |
|--------|----------|
| https://github.com/user-attachments/assets/3135b01b-48dd-4b60-a020-727957a9788f | https://github.com/user-attachments/assets/5c179375-b18a-4d1d-ad85-42069b66de35 |

Refresh bonds when their atoms are now selected

---

godot_project/autoloads/MolecularEditorContext.gd
godot_project/editor/controls/dockers/workspace_docker/a_create_docker/auto_create_bonds_panel.gd
godot_project/editor/controls/import_file_dialog/import_file_dialog.tscn
godot_project/project_workspace/file_format/external/xyz_format_loader.gd
godot_project/project_workspace/file_format/external/xyz_format_loader.gd.uid
godot_project/project_workspace/file_format/workspace_format_loader.gd
godot_project/utils/auto_bonder.gd
godot_project/utils/auto_bonder.gd.uid
godot_project/utils/workspace_utils.gd

Adds an XYZ resource loader (OpenMM doesn't support xyz so we have to provide our own implementation).
This PR also moves some of the code for automatic bond generation to a static utility script. I believe the PDB loader has a duplicate of that code, but I'm not sure it's actually in use so I didn't change it in this PR.

Adds ability to load XYZ files

---

godot_project/editor/ring_menu_levels/atoms/ring_action_select_element.gd
godot_project/editor/ring_menu_levels/atoms/ring_action_show_periodic_table.gd
godot_project/editor/ring_menu_levels/atoms/ring_action_show_periodic_table.gd.uid
godot_project/editor/ring_menu_levels/atoms/ring_level_atoms.gd

https://github.com/user-attachments/assets/5feb542b-ea37-446c-b933-6ebe76de6bb0
Task: No access to all atom types from RingMenu

Add a ring action to see the full periodic table of elements

---

godot_project/editor/controls/dockers/workspace_docker/c_dynamic_context_docker/dynamic_context_controls/selection_info.gd

Task: BUGS - New Godot version warning

Resolve warning about deprecated method `TreeItem.set_custom_draw()`
